name: Test Build and Push Image CI

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
    - uses: actions/checkout@v4
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Print workspace path
      run: |
        $dir = ($env:GITHUB_WORKSPACE).tostring()
        $parts = $dir.LastIndexOf("\")
        $dirname= $env:HOMEDRIVE+$dir.SubString($parts)
        echo "Dir_Name=$($env:HOMEDRIVE+$dir.SubString($parts))" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      env:
        GITHUB_TOKEN: ${{ github.token }}  
    # - name: Call a Bash Script
    #   run:  bash ${GITHUB_WORKSPACE}/run-unit-tests.sh
      
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    # - name: Log in to the Container registry
    #    uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
    #    with:
    #      registry: ${{ env.REGISTRY }}
    #      username: ${{ github.actor }}
    #      password: ${{ secrets.GITHUB_TOKEN }}
      
